"use server";
import { revalidatePath } from "next/cache";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { dateKey } from "@/lib/utils";
async function currentUser() { const session = await auth(); if (!session?.user?.email) throw new Error("Unauthorized"); const user = await prisma.user.findUnique({where:{email:session.user.email}}); if(!user) throw new Error("User not found"); return user; }
export async function toggleHabit(habitId:string, checked:boolean) { const user=await currentUser(); const habit=await prisma.habit.findFirst({where:{id:habitId,userId:user.id}}); if(!habit) throw new Error("Habit not found"); const date=new Date(`${dateKey()}T00:00:00.000Z`); if(checked) await prisma.habitCompletion.upsert({where:{habitId_date:{habitId,date}},update:{completedAt:new Date()},create:{habitId,date}}); else await prisma.habitCompletion.deleteMany({where:{habitId,date}}); revalidatePath("/dashboard"); revalidatePath("/progress"); }
export async function addHabit(formData:FormData) { const user=await currentUser(); const title=String(formData.get("title")||"").trim(); if(title.length<2) throw new Error("Habit name must be at least two characters"); const exists=await prisma.habit.findFirst({where:{userId:user.id,title:{equals:title,mode:"insensitive"},archivedAt:null}}); if(exists) throw new Error("A process with that name already exists"); const habit=await prisma.habit.create({data:{userId:user.id,title,frequency:"DAILY",color:"#7c3aed"}}); revalidatePath("/dashboard"); revalidatePath("/habits"); return {id:habit.id,title:habit.title}; }
export async function renameHabit(habitId:string,title:string) { const user=await currentUser(); const next=title.trim(); if(next.length<2) throw new Error("Process name must be at least two characters"); const habit=await prisma.habit.findFirst({where:{id:habitId,userId:user.id}}); if(!habit) throw new Error("Habit not found"); const exists=await prisma.habit.findFirst({where:{userId:user.id,title:{equals:next,mode:"insensitive"},id:{not:habitId},archivedAt:null}}); if(exists) throw new Error("A process with that name already exists"); const updated=await prisma.habit.update({where:{id:habitId},data:{title:next}}); revalidatePath("/dashboard"); revalidatePath("/habits"); return {id:updated.id,title:updated.title}; }
export async function deleteHabit(habitId:string) { const user=await currentUser(); const habit=await prisma.habit.findFirst({where:{id:habitId,userId:user.id}}); if(!habit) throw new Error("Habit not found"); await prisma.habit.delete({where:{id:habitId}}); revalidatePath("/dashboard"); revalidatePath("/habits"); }
export async function saveMood(formData:FormData) { const user=await currentUser(); const score=Number(formData.get("score")); if(score<1||score>5) throw new Error("Mood must be between 1 and 5"); const date=new Date(`${dateKey()}T00:00:00.000Z`); await prisma.moodEntry.upsert({where:{userId_date:{userId:user.id,date}},update:{score},create:{userId:user.id,date,score}}); revalidatePath("/dashboard"); }
export async function saveJournal(formData:FormData) { const user=await currentUser(); const content=String(formData.get("content")||"").trim(); if(!content) throw new Error("Journal entry cannot be empty"); const date=new Date(`${dateKey()}T00:00:00.000Z`); const entry=await prisma.journalEntry.create({data:{userId:user.id,date,content,includeInAi:formData.get("includeInAi")==="on"}}); revalidatePath("/journal"); revalidatePath("/dashboard"); return {id:entry.id,content:entry.content,date:entry.date.toISOString(),includeInAi:entry.includeInAi,createdAt:entry.createdAt.toISOString()}; }
export async function updateJournalEntry(entryId:string,content:string,includeInAi:boolean) { const user=await currentUser(); const next=content.trim(); if(!next) throw new Error("Journal entry cannot be empty"); const entry=await prisma.journalEntry.findFirst({where:{id:entryId,userId:user.id}}); if(!entry) throw new Error("Journal entry not found"); const updated=await prisma.journalEntry.update({where:{id:entryId},data:{content:next,includeInAi}}); revalidatePath("/journal"); revalidatePath("/dashboard"); return {id:updated.id,content:updated.content,includeInAi:updated.includeInAi}; }
export async function deleteJournalEntry(entryId:string) { const user=await currentUser(); const entry=await prisma.journalEntry.findFirst({where:{id:entryId,userId:user.id}}); if(!entry) throw new Error("Journal entry not found"); await prisma.journalEntry.delete({where:{id:entryId}}); revalidatePath("/journal"); revalidatePath("/dashboard"); }
export async function clearAllData(confirmation:string) { const user=await currentUser(); if(confirmation!=="CLEAR") throw new Error("Confirmation code must be CLEAR"); await prisma.$transaction([prisma.habit.deleteMany({where:{userId:user.id}}),prisma.goal.deleteMany({where:{userId:user.id}}),prisma.moodEntry.deleteMany({where:{userId:user.id}}),prisma.journalEntry.deleteMany({where:{userId:user.id}}),prisma.reminder.deleteMany({where:{userId:user.id}}),prisma.userAchievement.deleteMany({where:{userId:user.id}}),prisma.aiInsight.deleteMany({where:{userId:user.id}})]); for(const path of ["/dashboard","/habits","/calendar","/progress","/journal","/insights","/achievements"]) revalidatePath(path); }
export async function deleteAccount(confirmation:string) { const user=await currentUser(); if(confirmation!=="DELETE") throw new Error("Confirmation code must be DELETE"); await prisma.user.delete({where:{id:user.id}}); }
